version: "3.9"
services:
  mongo:
    image: mongo:5.0.6-focal
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
        - MONGO_INITDB_DATABASE=mongodb_simple